// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaEventosSonart.Data;

#nullable disable

namespace SistemaEventosSonart.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaEventosSonart.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SistemaEventosSonart.Models.Cotizacion", b =>
                {
                    b.Property<int>("CotizacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CotizacionId"));

                    b.Property<string>("EstadoCotizacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCotizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaqueteServicioId")
                        .HasColumnType("int");

                    b.Property<int>("SolicitudEventoId")
                        .HasColumnType("int");

                    b.HasKey("CotizacionId");

                    b.HasIndex("PaqueteServicioId");

                    b.HasIndex("SolicitudEventoId");

                    b.ToTable("Cotizaciones");
                });

            modelBuilder.Entity("SistemaEventosSonart.Models.PaqueteServicio", b =>
                {
                    b.Property<int>("PaqueteServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaqueteServicioId"));

                    b.Property<int>("CapacidadPersonas")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombrePaquete")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PaqueteServicioId");

                    b.ToTable("PaquetesServicio");
                });

            modelBuilder.Entity("SistemaEventosSonart.Models.ServicioAdicional", b =>
                {
                    b.Property<int>("ServicioAdicionalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServicioAdicionalId"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreServicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioReferencial")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ServicioAdicionalId");

                    b.ToTable("ServiciosAdicionales");
                });

            modelBuilder.Entity("SistemaEventosSonart.Models.SolicitudEvento", b =>
                {
                    b.Property<int>("SolicitudEventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitudEventoId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoSolicitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SolicitudEventoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("SolicitudesEvento");
                });

            modelBuilder.Entity("SistemaEventosSonart.Models.Cotizacion", b =>
                {
                    b.HasOne("SistemaEventosSonart.Models.PaqueteServicio", "PaqueteServicio")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("PaqueteServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaEventosSonart.Models.SolicitudEvento", "SolicitudEvento")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("SolicitudEventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaqueteServicio");

                    b.Navigation("SolicitudEvento");
                });

            modelBuilder.Entity("SistemaEventosSonart.Models.SolicitudEvento", b =>
                {
                    b.HasOne("SistemaEventosSonart.Models.Cliente", "Cliente")
                        .WithMany("SolicitudesEvento")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SistemaEventosSonart.Models.Cliente", b =>
                {
                    b.Navigation("SolicitudesEvento");
                });

            modelBuilder.Entity("SistemaEventosSonart.Models.PaqueteServicio", b =>
                {
                    b.Navigation("Cotizaciones");
                });

            modelBuilder.Entity("SistemaEventosSonart.Models.SolicitudEvento", b =>
                {
                    b.Navigation("Cotizaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
